# Generated by Django 4.2.11 on 2025-01-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
